### ISSUE TITLE
Timing dependency in views publishing

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1001]
Traceback (most recent call last):
      File "./script/publish_views", line 128, in <module>
        main()
      File "./script/publish_views", line 119, in main
        result = p.map(worker_entrypoint, sql_files, chunksize=1)
      File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
        raise self._value
      File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
        return list(map(*args))
      File "./script/publish_views", line 58, in process_file
        query_job.result()
      File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
        super(QueryJob, self).result(retry=retry, timeout=timeout)
      File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
        return super(_AsyncJob, self).result(timeout=timeout)
      File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 130, in result
        raise self._exception
    google.api_core.exceptions.BadRequest: 400 Invalid snapshot time 1590101920268 for table moz-fx-data-shared-prod:search.search_clients_last_seen_v1. Cannot read before 1590101920284
    
    (job ID: BLAH)
    
                      -----Query Job SQL Follows-----                  
    
        |    .    |    .    |    .    |    .    |    .    |    .    |
       1:CREATE OR REPLACE VIEW
       2:  `moz-fx-data-shared-prod.search.search_clients_last_seen`
       3:AS
       4:SELECT
       5:  *
       6:FROM
       7:  `moz-fx-data-shared-prod.search.search_clients_last_seen_v1`

This happened once before in https://github.com/mozilla/bigquery-etl/pull/928#issuecomment-618781873 so I'm filing an issue for it. It is trivial to run views publishing twice, but maybe there is something low effort we could do to prevent this. The timestamps in the errors have in both cases been under 100ms apart.

**Comment by whd** [comment]
Another thing worth noting is that this seems to only happen with `moz-fx-data-shared-prod:search.search_clients_last_seen` for whatever reason. These views aren't changing, but I would hazard to guess that it's because `moz-fx-data-shared-prod.search.search_clients_last_seen_v1` is being `CREATE OR REPLACE`d within milliseconds of `moz-fx-data-shared-prod.search.search_clients_last_seen` and so the replacement can't use the snapshot it took since the view changed.

If this is the only place where we have an unversioned view into a versioned view I would be surprised, but in the 3-4 times this has happened I think it's always been the same view.

**Comment by jklukas** [comment]
I think we should retry on these specific "Invalid snapshot time" exceptions.
