### ISSUE TITLE
publish_views google.api_core.exceptions.BadRequest: 400 GET Function not found: udf.normalize_search_engine

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1072]
/CC @Ben-Wu since #1062 appears to be the cause. `udf.normalize_search_engine` probably needs to be fully qualified since running the `CREATE OR REPLACE` from shared-prod works as expected.

```
Traceback (most recent call last):
  File "./script/publish_views", line 128, in <module>
    main()
  File "./script/publish_views", line 119, in main
    result = p.map(worker_entrypoint, sql_files, chunksize=1)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "./script/publish_views", line 58, in process_file
    query_job.result()
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 125, in result
    self._blocking_poll(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3098, in _blocking_poll
    super(QueryJob, self)._blocking_poll(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 104, in _blocking_poll
    retry_(self._done_or_raise)()
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 83, in _done_or_raise
    if not self.done():
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3079, in done
    self._query_results = self._client._get_query_results(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1286, in _get_query_results
    resource = self._call_api(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.8/site-packages/google/cloud/_http.py", line 423, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET Function not found: udf.normalize_search_engine at [38:3]

                  -----Query Job SQL Follows-----

    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod.search.search_aggregates`
   3:AS
   4:SELECT
   5:  submission_date_s3,
   6:  submission_date_s3 AS submission_date,
   7:  app_version,
   8:  country,
   9:  distribution_id,
  10:  engine,
  11:  locale,
  12:  search_cohort,
  13:  source,
  14:  default_search_engine,
  15:  IFNULL(organic, 0) AS organic,
  16:  IFNULL(tagged_sap, 0) AS tagged_sap,
  17:  IFNULL(tagged_follow_on, 0) AS tagged_follow_on,
  18:  IFNULL(sap, 0) AS sap,
  19:  IFNULL(ad_click, 0) AS ad_click,
  20:  IFNULL(search_with_ads, 0) AS search_with_ads,
  21:  IFNULL(unknown, 0) AS unknown,
  22:  addon_version,
  23:  os,
  24:  os_version,
  25:  IFNULL(client_count, 0) AS client_count,
  26:  NULL AS default_private_search_engine,
  27:  NULL AS normalized_engine,
  28:  NULL AS is_default_browser
  29:FROM
  30:  `moz-fx-data-derived-datasets.search.search_aggregates_v6`
  31:WHERE
  32:  submission_date_s3 >= '2019-05-04'
  33:  AND submission_date_s3 <= '2019-05-11'
  34:UNION ALL
  35:SELECT
  36:  submission_date AS submission_date_s3,
  37:  * EXCEPT (normalized_engine),
  38:  udf.normalize_search_engine(engine) AS normalized_engine,
  39:FROM
  40:  `moz-fx-data-shared-prod.search_derived.search_aggregates_v8`
  41:WHERE
  42:  submission_date < '2019-05-04'
  43:  OR submission_date > '2019-05-11'
```

**Comment by jklukas** [comment]
I would have expected the dry run to fail on this view. Previously, views were required to use fully-qualified names for all table and UDF references. BQ must have silently lifted that restriction recently.

**Comment by jklukas** [comment]
Captured the need for follow-up to protect against this in the future: https://github.com/mozilla/bigquery-etl/issues/1075
