### ISSUE TITLE
publish_persistent_udfs: moz-fx-data-derived-datasets:map was not found in location US

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1400]
```
+ ./script/publish_persistent_udfs --project-id moz-fx-data-derived-datasets
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/bigquery_etl/udf/publish_udfs.py", line 171, in <module>
    main()
  File "/app/bigquery_etl/udf/publish_udfs.py", line 73, in main
    publish(
  File "/app/bigquery_etl/udf/publish_udfs.py", line 102, in publish
    publish_udf(
  File "/app/bigquery_etl/udf/publish_udfs.py", line 156, in publish_udf
    client.query(query).result()
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3230, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 835, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 130, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset moz-fx-data-derived-datasets:map was not found in location US
```

This also happened in stage when publishing with `./script/publish_persistent_udfs --project-id moz-fx-data-shar-nonprod-efed`, but notably not with `--project-id moz-fx-data-shared-prod` (the most important case).

**Comment by whd** [comment]
Fixed by #1399
