### ISSUE TITLE
publish_views: google.api_core.exceptions.NotFound: 404 Not found: Dataset moz-fx-data-shared-prod:fetch was not found in location US

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1583]
/CC @Ben-Wu @scholtzan per #1575, not sure why this is trying to publish these to shared-prod

```
# cd /app
# cp -R sql /tmp/sql
# ./script/publish_views --target-project moz-fx-data-shared-prod /tmp/sql
[...]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/bigquery_etl/view/publish_views.py", line 149, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/bigquery_etl/view/publish_views.py", line 140, in main
    result = p.map(worker_entrypoint, sql_files, chunksize=1)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/app/bigquery_etl/view/publish_views.py", line 70, in _process_file
    query_job.result()
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1160, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 631, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset moz-fx-data-shared-prod:fetch was not found in location US

                                  -----Query Job SQL Follows-----                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod.fetch.latest_metric`
   3:AS
   4:SELECT
   5:  int64_field_0 AS fetch_id,
   6:  * EXCEPT (int64_field_0),
   7:FROM
   8:  `moz-fx-data-marketing-prod.fetch.metric_*`
   9:WHERE
  10:  _TABLE_SUFFIX = (SELECT MAX(_TABLE_SUFFIX) FROM `moz-fx-data-marketing-prod.fetch.metric_*`)
```

**Comment by Ben-Wu** [comment]
My suspicion is that this should be run with `/tmp/sql/moz-fx-data-shared-prod/` as the target directory.  Then we can run this per project we want to publish.  I can validate this tomorrow.

We can also make the publish script account for the directory structure.

**Comment by Ben-Wu** [comment]
I don't see any cases where we want to publish views from other projects into shared-prod.  I think the best thing to do here is to change the command to `./script/publish_views --target-project moz-fx-data-shared-prod /tmp/sql/moz-fx-data-shared-prod` (also for derived-datasets if that still happens) instead of adding projects to the skip list.

I'd like to get a second opinion @jklukas

**Comment by jklukas** [comment]
I agree that in effect we can only support "republishing" views defined in shared-prod, so it would be reasonable to redefine the command to:

```
./script/publish_views --target-project moz-fx-data-shared-prod /tmp/sql/moz-fx-data-shared-prod
./script/publish_views --target-project moz-fx-data-derived-datasets /tmp/sql/moz-fx-data-shared-prod
```

But I think I'd prefer to handle this in the `publish_views` logic. Rather than adding to the skip list, I think we should add some logic such that we ignore views outside shared-prod if `--target-project` is specified.

Something like this:

```
        if args.target_project:
            project_id = target_view_orig.replace("`", "").rsplit(".", 2)[0]
            if project_id != 'moz-fx-data-shared-prod':
                print(f"Skipping {filepath} because --target-project is set")
                return True
            target_view = target_view_orig.replace(project_id, args.target_project, 1)
            # We only change the first occurrence, which is in the target view name.
            sql = sql.replace(project_id, args.target_project, 1)
```

And then the invocation would become:

```
./script/publish_views /tmp/sql/
./script/publish_views --target-project moz-fx-data-derived-datasets /tmp/sql/
```

**Comment by whd** [comment]
> But I think I'd prefer to handle this in the `publish_views` logic. Rather than adding to the skip list, I think we should add some logic such that we ignore views outside shared-prod if `--target-project` is specified.

I agree with this statement.

**Comment by Ben-Wu** [comment]
Change has been merged so this should work now.  Publishing to other projects by not setting `--target-project` should also work as long as the service account has the right permissions.
