### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when using dry run service

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#1615]
Follow-up from Slack. When generating DAGs using `bqetl` a user encountered the following error: 

```
ERROR
 <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

Stacktrace:

```
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.8/bin/bqetl", line 11, in <module>
  load_entry_point('mozilla-bigquery-etl==20.12.1', 'console_scripts', 'bqetl')()
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/cli/__init__.py", line 42, in cli
  group(prog_name=prog_name)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
  return self.main(*args, **kwargs)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
  rv = self.invoke(ctx)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
  return callback(*args, **kwargs)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/cli/dag.py", line 176, in generate
  dags.to_airflow_dags(output_dir)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/query_scheduling/dag_collection.py", line 114, in to_airflow_dags
  p.map(partial(self.dag_to_airflow, output_dir), self.dags, chunksize=1)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
  return self._map_async(func, iterable, mapstar, chunksize).get()
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 768, in get
  raise self._value
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
  result = (True, func(*args, **kwds))
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
  return list(map(*args))
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/query_scheduling/dag_collection.py", line 106, in dag_to_airflow
  dag.to_airflow_dag(self), fast=False, mode=FileMode()
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/query_scheduling/dag.py", line 217, in to_airflow_dag
  task.with_dependencies(dag_collection)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/query_scheduling/task.py", line 363, in with_dependencies
  for table in self._get_referenced_tables():
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/query_scheduling/task.py", line 342, in _get_referenced_tables
  referenced_tables = DryRun(query_file).get_referenced_tables()
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bigquery_etl/dryrun.py", line 177, in get_referenced_tables
  raise Exception(f"Error when dry running SQL file {self.sqlfile}")
Exception: Error when dry running SQL file sql/moz-fx-data-shared-prod/telemetry_derived/core_clients_daily_v1/query.sql
```

**Comment by scholtzan** [comment]
This was a Python installation problem: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
