### ISSUE TITLE
publish views: Not found: Dataset moz-fx-data-terraform-admin:telemetry_stable was not found in location US

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1796]
/CC @fbertsch 
probably https://github.com/mozilla/bigquery-etl/pull/1664

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/bigquery_etl/view/publish_views.py", line 175, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/bigquery_etl/view/publish_views.py", line 166, in main
    result = p.map(worker_entrypoint, sql_files, chunksize=1)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/app/bigquery_etl/view/publish_views.py", line 81, in _process_file
    query_job.result()
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1159, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 631, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset ops_project:telemetry_stable was not found in location US

                      -----Query Job SQL Follows-----                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod`.telemetry_derived.deanonymized_events
   3:AS
   4:WITH events AS (
   5:  SELECT
   6:    `moz-fx-data-shared-prod`.udf.deanonymize_event(e).*,
   7:    *
   8:  FROM
   9:    telemetry_stable.event_v4 <----- this line
  10:  LEFT JOIN
  11:    UNNEST(
  12:      [
  13:        STRUCT("content" AS process, payload.events.content AS events),
  14:        ("dynamic", payload.events.dynamic),
  15:        ("extension", payload.events.extension),
  16:        ("gpu", payload.events.gpu),
  17:        ("parent", payload.events.parent)
  18:      ]
  19:    )
  20:  LEFT JOIN
  21:    UNNEST(events) AS e
  22:)
  23:SELECT
  24:  DATE(submission_timestamp) AS submission_date,
  25:  event_category AS category,
  26:  CONCAT(event_method, '.', event_object) AS event,
  27:  ARRAY_CONCAT(
  28:    event_map_values,
  29:    IF(
  30:      event_string_value IS NOT NULL,
  31:      [STRUCT('event_value' AS key, event_string_value AS value)],
  32:      []
  33:    )
  34:  ) AS extra,
  35:  SAFE.TIMESTAMP_ADD(
  36:    SAFE.TIMESTAMP_MILLIS(payload.process_start_timestamp),
  37:    INTERVAL event_timestamp MILLISECOND
  38:  ) AS timestamp,
  39:  (
  40:    SELECT
  41:      ARRAY_AGG(STRUCT(key, value.branch AS value))
  42:    FROM
  43:      UNNEST(environment.experiments)
  44:  ) AS experiments,
  45:  *
  46:FROM
  47:  events
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
```

**Comment by fbertsch** [comment]
Fixed with #1797
