### ISSUE TITLE
firefox_accounts_derived fxa_auth_bounce_events fails to run on 2021-05-19

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#2051]
Relevant airflow logs on 2021-05-19:

```
[2021-05-20 17:58:27,458] {pod_launcher.py:173} INFO - Event: firefox-accounts-derived--fxa-auth-bounce-events--v1-73185d7254f9439c97b00eb3a1e6b7e1 had an event of type Running
[2021-05-20 17:58:31,608] {pod_launcher.py:156} INFO - b"Error in query string: Error processing job 'moz-fx-data-shared-\n"
[2021-05-20 17:58:31,609] {pod_launcher.py:156} INFO - b"prod:bqjob_r4bfc12efdf2f7e1d_000001798aedc49e_1': Unrecognized name:\n"
[2021-05-20 17:58:31,610] {pod_launcher.py:156} INFO - b'jsonPayload; Did you mean textPayload? at [17:3]\n'
[2021-05-20 17:58:31,610] {pod_launcher.py:156} INFO - b'\rWaiting on bqjob_r4bfc12efdf2f7e1d_000001798aedc49e_1 ... (0s) Current status: RUNNING\r                                                                                      \rWaiting on bqjob_r4bfc12efdf2f7e1d_000001798aedc49e_1 ... (0s) Current status: DONE   \n'
[2021-05-20 17:58:31,780] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    return _run_code(code, main_globals, None,\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    exec(code, run_globals)\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/app/bigquery_etl/run_query.py", line 107, in <module>\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    main()\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/app/bigquery_etl/run_query.py", line 97, in main\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    run(\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/app/bigquery_etl/run_query.py", line 91, in run\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    subprocess.check_call(["bq"] + query_arguments, stdin=query_stream)\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call\n'
[2021-05-20 17:58:31,781] {pod_launcher.py:156} INFO - b'    raise CalledProcessError(retcode, cmd)\n'
```
https://workflow.telemetry.mozilla.org/log?task_id=firefox_accounts_derived__fxa_auth_bounce_events__v1&dag_id=bqetl_fxa_events&execution_date=2021-05-19T01%3A30%3A00%2B00%3A00

It looks like the schema is schema incompatible and solution in https://github.com/mozilla/bigquery-etl/issues/1684 may be relevant.

**Comment by jklukas** [comment]
It looks like the entire `jsonPayload` top-level field may be gone? I'll take a look at the source table.

**Comment by jklukas** [comment]
@jbuck - Any idea why the entire `jsonPayload` struct is missing from the 2021-05-20 partition of docker_fxa_auth_bounces?

**Comment by jklukas** [comment]
It looks like we haven't had any matching records ingested to this table since 2021-04-22. And I don't think auth bounce events are useful for tracking user activity anyway. I will deschedule this query for now until we can learn more from @jbuck.

**Comment by jklukas** [comment]
This query is now descheduled and the affected DAGs have now run to completion for 2021-05-19.

**Comment by jbuck** [comment]
@jklukas Thank you for filing this issue, it's completely because the process hasn't been starting successfully since 2021-04-22 😬

**Comment by jklukas** [comment]
Sounds like descheduling was a reasonable call then :)

I'm watching the Jira issue, and I'll go ahead and close this one.
