### ISSUE TITLE
publish views failure: java.lang.NullPointerException

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#2246]
/CC @scholtzan @relud as people likely to have context

I didn't see anything in the logs up to this point that was unusual.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/bigquery_etl/cli/__init__.py", line 56, in cli
    group(prog_name=prog_name)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/bigquery_etl/cli/view.py", line 202, in publish
    result = p.map(publish_view, views, chunksize=1)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/app/bigquery_etl/cli/view.py", line 211, in _publish_view
    return view.publish(target_project, dry_run)
  File "/app/bigquery_etl/view/__init__.py", line 195, in publish
    if self.is_valid():
  File "/app/bigquery_etl/view/__init__.py", line 134, in is_valid
    return self._valid_fully_qualified_references() and self._valid_view_naming()
  File "/app/bigquery_etl/view/__init__.py", line 140, in _valid_fully_qualified_references
    for table in extract_table_references(self.content):
  File "/app/bigquery_etl/dependency.py", line 45, in extract_table_references
    options.getLanguageOptions().setSupportsAllStatementKinds()
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 954, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException
```

**Comment by whd** [comment]
This appears to be transient, as I re-ran the job today and it worked. I'll close this for now and re-open if additional investigation is warranted (e.g. high incidence frequency).

**Comment by whd** [comment]
Reopening with a similarly transient but java-ish failure from today:

```
+ ./script/publish_views --target-project moz-fx-data-shared-prod /tmp/sql
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/app/target/dependency/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdfe9bbcfc6, pid=350, tid=359
#
# JRE version: OpenJDK Runtime Environment (11.0.12+7) (build 11.0.12+7-post-Debian-2deb10u1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.12+7-post-Debian-2deb10u1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x8b4fc6]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /app/core.350)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid350.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.debian.org/openjdk-11
#
Aborted (core dumped)
```

**Comment by scholtzan** [comment]
@relud Does this look familiar to you?

**Comment by relud** [comment]
I have not seen this before. The warning is likely unrelated.

**Comment by whd** [comment]
This happened again with today's schemas deploy (but only mozdata and not shared-prod). I'm not sure what additional debugging information to provide, or whether it can be reproduced without actually trying to redeploy all views.

**Comment by scholtzan** [comment]
I did some testing and it seems like views that should be skipped when publishing are trying to get published when running this for mozdata. This is causing some failures. I'll push a fix for that.
