### ISSUE TITLE
glam queries have invalid schema.yaml

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2274]
The glam ETL schema.yaml files such as https://github.com/mozilla/bigquery-etl/blob/main/sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_histogram_aggregates_metrics_v1/schema.yaml contain list of fields, but this should be nested under a top-level `fields` key.

cc @acmiyaguchi

**Comment by acmiyaguchi** [comment]
What command did you use to verify that the schemas were invalid?

**Comment by jklukas** [comment]
This was while attempting to follow the cookbook for adding a field to clients_daily. Particularly:

```
bqetl query schema update telemetry_derived.clients_daily_v6 --update_downstream
```

That raised errors when parsing the glam schema files.

**Comment by jklukas** [comment]
```
Traceback (most recent call last):
  File "/Users/jeffklukas/Code/bigquery-etl/venv/bin/bqetl", line 33, in <module>
    sys.exit(load_entry_point('mozilla-bigquery-etl', 'console_scripts', 'bqetl')())
  File "/Users/jeffklukas/Code/bigquery-etl/bigquery_etl/cli/__init__.py", line 56, in cli
    group(prog_name=prog_name)
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeffklukas/Code/bigquery-etl/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jeffklukas/Code/bigquery-etl/bigquery_etl/cli/query.py", line 791, in update
    changed = _update_query_schema(
  File "/Users/jeffklukas/Code/bigquery-etl/bigquery_etl/cli/query.py", line 1008, in _update_query_schema
    query_schema.merge(table_schema)
  File "/Users/jeffklukas/Code/bigquery-etl/bigquery_etl/schema/__init__.py", line 97, in merge
    self.schema["fields"],
KeyError: 'fields'
```

**Comment by jklukas** [comment]
And for posterity, having a top-level "fields" array makes these schema.yaml files match the API format specified in https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableSchema

It's a bit confusing, though, considering that the `bq show --schema mytable` command returns a JSON list rather than an object containing a top-level "fields" array.
