### ISSUE TITLE
Views deploy ImportError: failed to import java class via jni, please build java dependencies with: mvn package

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#2878]
This failed for the most recent views deploy, using the private GCR container.

/CC @ANich (most recent code change) and @relud (I vaguely recall something mvn related landing this week)

```
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/app/bigquery_etl/dependency.py", line 35, in extract_table_references
    ZetaSqlHelper = jnius.autoclass("com.mozilla.telemetry.ZetaSqlHelper")
  File "/usr/local/lib/python3.8/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: com.google.zetasql.ClientChannelProvider: Provider com.google.zetasql.JniChannelProvider could not be instantiated java.util.ServiceConfigurationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 94, in _generate_view_schema
    reference_path = _get_reference_dir_path(view_directory)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 41, in _get_reference_dir_path
    view_references = extract_table_references(view_file.read_text())
  File "/app/bigquery_etl/dependency.py", line 38, in extract_table_references
    raise ImportError(
ImportError: failed to import java class via jni, please build java dependencies with: mvn package
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/bigquery_etl/cli/__init__.py", line 52, in cli
    group(prog_name=prog_name)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 180, in generate
    pool.map(
  File "/usr/local/lib/python3.8/site-packages/pathos/multiprocessing.py", line 139, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
ImportError: failed to import java class via jni, please build java dependencies with: mvn package
[Pipeline] }
```

**Comment by whd** [comment]
From what I can tell from attempting to reproduce this on Jenkins, this issue may have been transient and may only affect error paths. I think it's reasonable to try re-upgrading to the latest version and seeing if it errors, or else wait to see if the next transient failure also has an error message like this.

**Comment by whd** [comment]
This started happening again. @relud do you think it could be because of https://github.com/mozilla/bigquery-etl/commit/93c17b7e6d40afc4067e4f0b62dc3b9551ec163e? My last comment says "may only affect error paths" so maybe the two recent commits to this repo introduced such an error, but I don't see why any reasoning as to why I came to that conclusion.


```
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/app/bigquery_etl/dependency.py", line 35, in extract_table_references
    ZetaSqlHelper = jnius.autoclass("com.mozilla.telemetry.ZetaSqlHelper")
  File "/usr/local/lib/python3.8/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: com.google.zetasql.ClientChannelProvider: Provider com.google.zetasql.JniChannelProvider could not be instantiated java.util.ServiceConfigurationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 94, in _generate_view_schema
    reference_path = _get_reference_dir_path(view_directory)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 41, in _get_reference_dir_path
    view_references = extract_table_references(view_file.read_text())
  File "/app/bigquery_etl/dependency.py", line 38, in extract_table_references
    raise ImportError(
ImportError: failed to import java class via jni, please build java dependencies with: mvn package
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/bigquery_etl/cli/__init__.py", line 52, in cli
    group(prog_name=prog_name)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/sql_generators/derived_view_schemas/__init__.py", line 180, in generate
    pool.map(
  File "/usr/local/lib/python3.8/site-packages/pathos/multiprocessing.py", line 139, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
ImportError: failed to import java class via jni, please build java dependencies with: mvn package
```

**Comment by relud** [comment]
> This started happening again. @relud do you think it could be because of [93c17b7](https://github.com/mozilla/bigquery-etl/commit/93c17b7e6d40afc4067e4f0b62dc3b9551ec163e)?

i don't see why it would, but i also don't see any harm in reverting it to find out

**Comment by whd** [comment]
I'm going to try re-running a few times since this was transient last time.

**Comment by whd** [comment]
Manually triggered deploy succeeded :shrug: 

For me next time: wait an hour before further investigation
